---
name: entity-relationship-diagram build and deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false  # Explicitly disable cache (we don't have a lockfile)

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build:web

      - name: Prepare deployment folder
        run: |
          mkdir public
          cp index.html public/
          cp -r css public/css
          cp -r js public/js
          cp -r dist public/dist

      - name: Save website content as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
